# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=500),
        ),
    ]
