# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-09 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_auto_20181109_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveTheItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_choice', models.CharField(default='', max_length=100)),
                ('many_items', models.IntegerField()),
                ('crime_type', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=500),
        ),
    ]
